import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wkVgkdHXHUTAGAACDghBAAPBgiTAGABABABeDAAg1TAGABAEg-AaTAGABAEghBAAQAgiACBAAABCBCCCLhaTAPdCg5TAJAEgjAg1glheXAIAABGg5gthRBAAAEAXAAAHgsDhfHAgjiSggdAPBHDCACBGCDMLAwZzJADQOQOQJACOgilddgwScgrhTWIgsFBi9ggQGg9WMBKCBgjbgjgoC4Iu2DAWcdDDCHAAeghhVXNWhBCCgjgsEBIJEGgig2PACFACgxgxIjUNBAAI14kAODACAcwXcgkhUgihWfcAPddghhUJAYhXCAAADAOAJQgkg1TAGABAEjTgmhZggjdggheghhZggMAhGajughmBgig5gngognmJgghCdh7gkg6dlVR');
