import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wW-AAABABAIaDFnKgqIBDACXDAIACAGOAYEAxevA4NsMAAJAMAEAAABABAJwyvFBAAgrABCABWAhHHIgvSABEggDZEAg_g3DTBguODACAcJIGIGg_fgkFLIg1JVBaEZGDLGhPhIg2gyMgyGFn_gni3W4NgIjEBIgvhDGADJDB');
